services:
  postgres:
    image: postgres:latest
    container_name: portgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

volumes:
  postgres:
    name: postgres
  
networks:
  default:
    name: mywebapp